version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: pre-release
    schedule:
      interval: weekly
    groups:
      npm:
        patterns: ['*']
  - package-ecosystem: github-actions
    directory: /
    target-branch: pre-release
    schedule:
      interval: weekly
